from __future__ import annotations

from app.core.config import get_settings
from app.models import Source
from app.services.collectors.base import ConnectorUnconfigured, RawDocumentCandidate


class AmazonSPAPICollector:
    provider = "amazon_sp_api"

    def __init__(self, db) -> None:
        self.db = db
        self.settings = get_settings()

    async def fetch(self, source: Source) -> list[RawDocumentCandidate]:
        configured = all(
            [
                self.settings.amazon_sp_api_client_id,
                self.settings.amazon_sp_api_client_secret,
                self.settings.amazon_sp_api_refresh_token,
            ]
        )
        if not configured:
            raise ConnectorUnconfigured(self.provider)
        return []


class AmazonSPAPIMockCollector:
    provider = "amazon_sp_api_mock"

    async def fetch(self, source: Source) -> list[RawDocumentCandidate]:
        category = (source.metadata_ or {}).get("category", "demo category")
        return [
            RawDocumentCandidate(
                url=f"https://example.com/demo/amazon-sp-api/{category}",
                title=f"[DEMO] Amazon SP-API signal for {category}",
                snippet="Demo-only placeholder generated by the mock adapter.",
                raw_content="Demo-only Amazon SP-API mock response. Not a real market conclusion.",
                content_type="amazon_sp_api_mock",
                metadata={"demo": True, "provider": self.provider, "category": category},
            )
        ]
